### ISSUE TITLE
humanTyping throws error on any OS

### ISSUE THREAD

**Issue by mwbelt** [NikolaiT/stealthy-scraping-tools#3]
I've tried multiple setups on different OS's, but I always wind up with the same error:

ImportError: cannot import name 'humanTyping' from 'typing'

**Comment by manickbhan** [comment]
you just need to change the import statement, that file existed when the repo was created initially but it was refactored

should be: `from behavior.behavior import humanMove, humanTyping`

Not sure if @NikolaiT has any other recent commits. 

Also check this article:
https://www.mattzeunert.com/2018/07/21/running-headful-chrome-on-ubuntu-server.html

**Comment by NikolaiT** [comment]
Thanks man @[manickbhan](https://github.com/manickbhan)
